"""
/***************************************************************************
 Biblizou_worker
                                 A QGIS plugin
 Module pour télécharger les xml des zonages Natura 2000 dans un périmètre donné. Compatible avec Biblizou ou exécution indépendante.
 Date de création : 2025/02
 Dernière mise à jour : 2026/01
 Version : 1.0

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by François Botcazou
        email                : francois.botcazou@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import requests
import time
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFeatureRequest,
    QgsMessageLog,
    QgsCoordinateTransform,
    QgsGeometry,
    Qgis
)
from PyQt5.QtWidgets import QInputDialog, QMessageBox


class NaturaDwlXml:
    def __init__(self):
        """Initialisation de la classe."""
        # Recherche des couches Patrinat dans le projet
        self.patrinat_sic = None
        self.patrinat_zps = None
        
        # Variables pour le traitement
        self.id_mnhn_sic = []
        self.id_mnhn_zps = []
        self.ae_eloignee = None
        self.download_folder = None
        self.files_downloaded = 0
        
    def run(self):
        """Point d'entrée principal du module (mode indépendant avec boîtes de dialogue)."""
        # 1. Rechercher les couches Patrinat
        if not self.find_patrinat_layers():
            return
            
        # 2. Sélection de la couche de référence
        if not self.select_layer_dialog():
            return
            
        # 3. Sélection du dossier de téléchargement
        if not self.select_download_folder_dialog():
            return
            
        # 4. Exécution du téléchargement
        success = self.execute_download()
        
        # 5. Affichage du résumé
        if success:
            self.show_summary()
    
    def run_with_params(self, natura_layer, folder_path):
        """
        Point d'entrée pour BiblizouMain (sans boîtes de dialogue).
        
        Args:
            natura_layer (QgsVectorLayer): Couche Natura 2000 de référence
            folder_path (str): Chemin du dossier de téléchargement
        Returns:
            bool: True si le téléchargement a réussi, False sinon
        """
        try:
            # Rechercher les couches Patrinat
            if not self.find_patrinat_layers():
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couches Patrinat SIC ou ZPS introuvables",
                    "Biblizou",
                    level=Qgis.Warning
                )
                return False
                
            # Définir les paramètres
            self.ae_eloignee = natura_layer
            self.download_folder = folder_path
            
            # Vérifier les paramètres
            if not self.ae_eloignee:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couche Natura 2000 de référence non définie",
                    "Biblizou",
                    level=Qgis.Warning
                )
                return False
                
            if not os.path.isdir(self.download_folder):
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Dossier introuvable: {self.download_folder}",
                    "Biblizou",
                    level=Qgis.Warning
                )
                return False
                
            # Exécuter le téléchargement
            return self.execute_download()
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Erreur lors du téléchargement: {str(e)}",
                "Biblizou",
                level=Qgis.Critical
            )
            return False
    
    def find_patrinat_layers(self):
        """Recherche les couches Patrinat dans le projet."""
        try:
            # Recherche des couches Patrinat
            sic_layers = QgsProject.instance().mapLayersByName("Patrinat : SIC")
            zps_layers = QgsProject.instance().mapLayersByName("Patrinat : ZPS")
            
            if sic_layers:
                self.patrinat_sic = sic_layers[0]
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couche Patrinat SIC trouvée",
                    "Biblizou",
                    level=Qgis.Info
                )
            else:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couche Patrinat SIC introuvable",
                    "Biblizou",
                    level=Qgis.Warning
                )
                
            if zps_layers:
                self.patrinat_zps = zps_layers[0]
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couche Patrinat ZPS trouvée",
                    "Biblizou",
                    level=Qgis.Info
                )
            else:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Couche Patrinat ZPS introuvable",
                    "Biblizou",
                    level=Qgis.Warning
                )
                
            return self.patrinat_sic is not None and self.patrinat_zps is not None
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Erreur lors de la recherche des couches Patrinat: {str(e)}",
                "Biblizou",
                level=Qgis.Critical
            )
            return False
    
    def select_layer_dialog(self):
        """Sélectionne une couche via boîte de dialogue (mode indépendant)."""
        try:
            layers = [layer.name() for layer in QgsProject.instance().mapLayers().values()]
            
            if not layers:
                QMessageBox.warning(
                    None,
                    "Erreur",
                    "Aucune couche disponible dans le projet."
                )
                return False
                
            selected_layer, ok = QInputDialog.getItem(
                None,
                "Sélection de la couche",
                "Choisissez une couche de référence :",
                layers,
                0,
                False
            )
            
            if not ok or not selected_layer:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Annulation par l'utilisateur (sélection de couche)",
                    "Biblizou",
                    level=Qgis.Info
                )
                return False
                
            selected_layers = QgsProject.instance().mapLayersByName(selected_layer)
            
            if selected_layers:
                self.ae_eloignee = selected_layers[0]
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Couche sélectionnée: {selected_layer}",
                    "Biblizou",
                    level=Qgis.Info
                )
                return True
            else:
                QMessageBox.warning(
                    None,
                    "Erreur",
                    f"La couche '{selected_layer}' est introuvable."
                )
                return False
                
        except Exception as e:
            QMessageBox.critical(
                None,
                "Erreur",
                f"Erreur lors de la sélection de la couche: {str(e)}"
            )
            return False
    
    def select_download_folder_dialog(self):
        """Sélectionne un dossier via boîte de dialogue (mode indépendant)."""
        try:
            download_folder, ok = QInputDialog.getText(
                None,
                "Chemin vers le dossier de travail",
                "Copier/coller le chemin du dossier de téléchargement :"
            )
            
            if not ok or not download_folder:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Annulation par l'utilisateur (sélection de dossier)",
                    "Biblizou",
                    level=Qgis.Info
                )
                return False
                
            if not os.path.isdir(download_folder):
                QMessageBox.warning(
                    None,
                    "Erreur",
                    f"Le dossier '{download_folder}' n'existe pas."
                )
                return False
                
            self.download_folder = download_folder
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Dossier sélectionné: {download_folder}",
                "Biblizou",
                level=Qgis.Info
            )
            return True
            
        except Exception as e:
            QMessageBox.critical(
                None,
                "Erreur",
                f"Erreur lors de la sélection du dossier: {str(e)}"
            )
            return False
    
    def selectionner_et_stocker(self, couche_source, liste_stockage):
        """Sélectionne les entités intersectant AE_eloignee et stocke leurs ID."""
        if not couche_source or not self.ae_eloignee:
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Couche source ou AE_eloignee introuvable",
                "Biblizou",
                level=Qgis.Warning
            )
            return
        
        try:
            # Définir la transformation de coordonnées
            transform = QgsCoordinateTransform(
                self.ae_eloignee.crs(),
                couche_source.crs(),
                QgsProject.instance()
            )
            
            # Fusionner toutes les géométries de AE_eloignee en une seule
            geometries = [f.geometry() for f in self.ae_eloignee.getFeatures()]
            
            if not geometries:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Aucune géométrie trouvée dans AE_eloignee",
                    "Biblizou",
                    level=Qgis.Warning
                )
                return
            
            geom_ref = QgsGeometry.unaryUnion(geometries)
            geom_ref.transform(transform)
            
            couche_source.removeSelection()
            ids_selectionnes = []
            liste_stockage.clear()
            
            # Effectuer une sélection spatiale
            request = QgsFeatureRequest().setFilterRect(geom_ref.boundingBox())
            
            for feature in couche_source.getFeatures(request):
                if feature.geometry().intersects(geom_ref):
                    ids_selectionnes.append(feature.id())
                    id_mnhn = feature["id_mnhn"]
                    if id_mnhn:
                        liste_stockage.append(str(id_mnhn))
            
            if ids_selectionnes:
                couche_source.selectByIds(ids_selectionnes)
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: {len(ids_selectionnes)} entités sélectionnées dans {couche_source.name()}",
                    "Biblizou",
                    level=Qgis.Info
                )
            else:
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Aucune entité sélectionnée dans {couche_source.name()}",
                    "Biblizou",
                    level=Qgis.Warning
                )
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Erreur lors de la sélection: {str(e)}",
                "Biblizou",
                level=Qgis.Critical
            )
    
    def download_file(self, url, save_path, retries=3):
        """Télécharge un fichier XML avec gestion des erreurs."""
        attempt = 0
        while attempt < retries:
            try:
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Tentative {attempt + 1} pour {url}",
                    "Biblizou",
                    level=Qgis.Info
                )
                
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                
                with open(save_path, 'wb') as f:
                    f.write(response.content)
                    
                self.files_downloaded += 1
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Fichier téléchargé avec succès: {save_path}",
                    "Biblizou",
                    level=Qgis.Success
                )
                return True
                
            except requests.exceptions.RequestException as e:
                attempt += 1
                wait_time = 2 ** attempt
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Échec tentative {attempt} pour {url}: {str(e)}",
                    "Biblizou",
                    level=Qgis.Warning
                )
                time.sleep(wait_time)
                
        QgsMessageLog.logMessage(
            f"NaturaDwlXml: Échec du téléchargement après {retries} tentatives: {url}",
            "Biblizou",
            level=Qgis.Critical
        )
        return False
    
    def construct_url_and_download(self, natura_ids):
        """Construit les URLs et télécharge les fichiers XML correspondants."""
        if not natura_ids:
            QgsMessageLog.logMessage(
                "NaturaDwlXml: Aucun identifiant Natura 2000 trouvé",
                "Biblizou",
                level=Qgis.Warning
            )
            return False
        
        total_ids = len(natura_ids)
        success_count = 0
        
        for i, natura_id in enumerate(natura_ids):
            # Log de progression
            if (i + 1) % 5 == 0 or i == 0 or i == total_ids - 1:
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Progression: {i + 1}/{total_ids}",
                    "Biblizou",
                    level=Qgis.Info
                )
            
            url = f"https://inpn.mnhn.fr/docs/natura2000/fsdxml/{natura_id}.xml"
            save_path = os.path.join(self.download_folder, f"{natura_id}.xml")
            
            if self.download_file(url, save_path):
                success_count += 1
        
        return success_count > 0
    
    def execute_download(self):
        """Exécute le processus complet de téléchargement."""
        try:
            # Réinitialiser les compteurs
            self.id_mnhn_sic.clear()
            self.id_mnhn_zps.clear()
            self.files_downloaded = 0
            
            # Sélectionner et stocker les IDs
            self.selectionner_et_stocker(self.patrinat_sic, self.id_mnhn_sic)
            self.selectionner_et_stocker(self.patrinat_zps, self.id_mnhn_zps)
            
            total_ids = len(self.id_mnhn_sic) + len(self.id_mnhn_zps)
            
            if total_ids == 0:
                QgsMessageLog.logMessage(
                    "NaturaDwlXml: Aucun site Natura 2000 intersectant la zone d'étude",
                    "Biblizou",
                    level=Qgis.Warning
                )
                return False
            
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: {total_ids} fichiers à télécharger",
                "Biblizou",
                level=Qgis.Info
            )
            
            # Télécharger les fichiers
            all_ids = self.id_mnhn_sic + self.id_mnhn_zps
            success = self.construct_url_and_download(all_ids)
            
            if success:
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Téléchargement terminé - {self.files_downloaded}/{total_ids} fichiers téléchargés",
                    "Biblizou",
                    level=Qgis.Success
                )
            else:
                QgsMessageLog.logMessage(
                    f"NaturaDwlXml: Échec du téléchargement",
                    "Biblizou",
                    level=Qgis.Critical
                )
            
            return success
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"NaturaDwlXml: Erreur lors de l'exécution: {str(e)}",
                "Biblizou",
                level=Qgis.Critical
            )
            return False
    
    def show_summary(self):
        """Affiche un résumé du téléchargement (mode indépendant uniquement)."""
        total_ids = len(self.id_mnhn_sic) + len(self.id_mnhn_zps)
        
        summary = (
            f"Résultats du téléchargement Natura 2000:\n\n"
            f"• Sites SIC intersectants: {len(self.id_mnhn_sic)}\n"
            f"• Sites ZPS intersectants: {len(self.id_mnhn_zps)}\n"
            f"• Total des fichiers: {total_ids}\n"
            f"• Fichiers téléchargés: {self.files_downloaded}\n\n"
            f"Dossier: {self.download_folder}\n\n"
            f"✓ Les fichiers XML sont prêts pour le traitement"
        )
        
        QMessageBox.information(
            None,
            "Téléchargement Natura 2000 terminé",
            summary
        )


# Pour exécuter le module dans QGIS
def run_module():
    """Fonction d'exécution pour QGIS (mode indépendant)."""
    module = NaturaDwlXml()
    module.run()


def run_module_with_params(natura_layer, folder_path):
    """
    Fonction d'exécution pour BiblizouMain.
    
    Args:
        natura_layer (QgsVectorLayer): Couche Natura 2000 de référence
        folder_path (str): Chemin du dossier de téléchargement
    Returns:
        bool: True si le téléchargement a réussi, False sinon
    """
    module = NaturaDwlXml()
    return module.run_with_params(natura_layer, folder_path)


# Exécution
if __name__ == "__console__":
    # Mode console: exécuter en mode indépendant
    run_module()