"""
/***************************************************************************
 NaturaPivotEspeces
                                 A QGIS plugin
 Module pour télécharger les xml des zonages Natura 2000 dans un périmètre donné. Compatible avec Biblizou ou exécution indépendante.
 Date de création : 2025/03
 Dernière mise à jour : 2026/01
 Version : 1.1

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by François Botcazou
        email                : francois.botcazou@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import unicodedata
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsMessageLog,
    Qgis
)
from PyQt5.QtWidgets import QMessageBox

class NaturaPivotEspeces:
    """Classe pour créer un tableau croisé unique pour toutes les espèces Natura 2000."""
    
    def __init__(self, source_layer_name="Natura_2000_Especes"):
        """Initialisation."""
        self.source_layer_name = source_layer_name
        self.output_layer_name = "Natura_2000_Especes_Pivot"
        
        # Mapping des groupes taxonomiques
        self.group_mapping = {
            'A': 'Amphibiens', 'B': 'Oiseaux', 'F': 'Poissons', 'Fu': 'Champignons',
            'I': 'Invertebres', 'L': 'Lichens', 'M': 'Mammiferes', 'P': 'Plantes', 'R': 'Reptiles'
        }

    def remove_accents(self, text):
        """Supprime les accents d'une chaîne de caractères."""
        if not text:
            return text
        # Normalisation NFD (décomposition) puis suppression des marques diacritiques
        nfd = unicodedata.normalize('NFD', str(text))
        return ''.join(char for char in nfd if unicodedata.category(char) != 'Mn')

    def run(self, show_gui=False):
        """
        Args:
            show_gui (bool): Si True, affiche des popups (mode indépendant).
        """
        source_layers = QgsProject.instance().mapLayersByName(self.source_layer_name)
        if not source_layers:
            msg = f"Couche source '{self.source_layer_name}' introuvable."
            QgsMessageLog.logMessage(msg, "Biblizou", level=Qgis.Warning)
            if show_gui: QMessageBox.warning(None, "Erreur", msg)
            return False

        layer = source_layers[0]
        
        # Création du pivot unique
        success = self.create_pivot(layer)
        
        if show_gui and success:
            self.show_summary()
            
        return success

    def create_pivot(self, layer):
        """Crée une couche virtuelle pivot unique pour tous les groupes."""
        
        # 1. Identifier tous les sites uniques pour les colonnes
        idx_code = layer.fields().indexOf('SITECODE')
        if idx_code == -1: idx_code = layer.fields().indexOf('sitecode')
        
        idx_name = layer.fields().indexOf('SITE_NAME')
        if idx_name == -1: idx_name = layer.fields().indexOf('SITENAME')
        if idx_name == -1: idx_name = layer.fields().indexOf('sitename')
        if idx_name == -1: idx_name = layer.fields().indexOf('siteName')
        
        unique_sites = {}
        for feat in layer.getFeatures():
            # On récupère les valeurs de manière sécurisée via les index
            s_code = feat.attributes()[idx_code] if idx_code != -1 else "Inconnu"
            s_name = feat.attributes()[idx_name] if idx_name != -1 else "Sans nom"
            unique_sites[s_code] = s_name
        
        if not unique_sites:
            QgsMessageLog.logMessage("Aucun site trouvé", "Biblizou", level=Qgis.Warning)
            return False

        # On utilise l'ID de la couche source
        layer_id = layer.id()
        
        query = "SELECT TAXGROUP AS GROUPE, CD_NOM, NOM"
        
        sql_parts = []
        for code, name in sorted(unique_sites.items()):
            # NOM_SITE : majuscules et sans accents (à, â, é, è, ë, ê, î, ô, ù...)
            nom_site = self.remove_accents(str(name)).upper()
            safe_code = str(code).replace("'", "''")
            col_name = f"{code} - {nom_site}".replace('"', '""')
            
            sql_parts.append(f', MAX(CASE WHEN SITECODE = \'{safe_code}\' THEN 1 ELSE NULL END) AS "{col_name}"')

        query += ''.join(sql_parts)
        
        # Requête avec GROUPE comme première colonne et tri par GROUPE puis NOM
        query += f' FROM "{layer_id}"'
        query += " GROUP BY TAXGROUP, CD_NOM, NOM"
        query += " ORDER BY TAXGROUP ASC, NOM ASC"

        # Log de la requête pour débogage
        QgsMessageLog.logMessage(f"Requête SQL (début) : {query[:500]}", "Biblizou", level=Qgis.Info)

        vlayer = QgsVectorLayer(f"?query={query}", self.output_layer_name, "virtual")
        
        if vlayer.isValid():
            # Nettoyage si existe déjà
            existing = QgsProject.instance().mapLayersByName(self.output_layer_name)
            for old in existing:
                QgsProject.instance().removeMapLayer(old.id())
            
            QgsProject.instance().addMapLayer(vlayer)
            QgsMessageLog.logMessage(f"Pivot créé : {self.output_layer_name}", "Biblizou", level=Qgis.Info)
            return True
        else:
            QgsMessageLog.logMessage("Erreur SQL pivot unifié", "Biblizou", level=Qgis.Critical)
            return False

    def show_summary(self):
        """Résumé pour le mode indépendant."""
        msg = f"Tableau croisé Natura 2000 créé :\n• {self.output_layer_name}\n"
        msg += "• Colonnes : [code] - [NOM_SITE] (majuscules, sans accents)"
        QMessageBox.information(None, "Succès", msg)

# --- FONCTION D'INTÉGRATION POUR BIBLIZOU_WORKER ---
def run_module():
    """Appelé par biblizou_worker.py"""
    pivot = NaturaPivotEspeces()
    # On met show_gui=False pour ne pas bloquer le thread FSD de biblizou_worker
    return pivot.run(show_gui=False)

if __name__ == "__main__":
    # Permet de tester le script seul dans la console QGIS
    pivot = NaturaPivotEspeces()
    pivot.run(show_gui=True)