# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Biblizou_worker
                                 A QGIS plugin
 Moissonnage bibliographique automatisé
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by François Botcazou
        email                : francois.botcazou@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from qgis.PyQt.QtCore import QThread, pyqtSignal

# WFS Manager
from .modules.WfsManager import setup_wfs_connections, load_wfs_layers

# Import des modules Natura 2000
from .modules.NaturaDwlXml import run_module_with_params as natura_download
from .modules.NaturaXmlToLayerDesc import run_module_with_path as natura_process_desc
from .modules.NaturaXmlToLayerHab import run_module_with_path as natura_process_hab
from .modules.NaturaPivotHabitats import run_module as natura_pivot_hab
from .modules.NaturaXmlToLayerEsp import run_module_with_path as natura_process_esp
from .modules.NaturaPivotEspeces import run_module as natura_pivot_esp

# Import des modules ZNIEFF
from .modules.ZnieffDwlXml import run_module_with_params as znieff_download
from .modules.ZnieffXmlToLayerDesc import run_module_with_path as znieff_process_desc
from .modules.ZnieffXmlToLayerHab import run_module_with_path as znieff_process_hab
from .modules.ZnieffPivotHabitats import run_module as znieff_pivot_hab
from .modules.ZnieffXmlToLayerEsp import run_module_with_path as znieff_process_esp
from .modules.ZnieffPivotEspeces import run_module as znieff_pivot_esp

# API TaxRef -> table data_taxref
from .modules.TaxrefApiToTable import TaxrefApiToTable

# BD Statuts (API TaxRef Statuts)
from .modules.StatusApiToTable import run as status_api_to_table
from .modules.StatusJoinTaxref import run as status_join_taxref
from .modules.StatusPivotByGroup import run as status_pivot_by_group

from .modules.BuildJulveDf import BuildJulveDf


class FsdProcessingThread(QThread):
    """Thread gérant le workflow complet des données FSD (Natura 2000 + ZNIEFF)."""
    progress = pyqtSignal(int, int, str)
    log = pyqtSignal(str)
    finished = pyqtSignal(str)
    error = pyqtSignal(str)

    def __init__(self, params, iface):
        super().__init__()
        self.params = params
        self.iface = iface
        # Initialisation des variables d'instance
        self.working_folder = None

    def run(self):
        try:
            self.log.emit(f"=== Démarrage du workflow FSD ===")
            self.log.emit(f"Params reçus: {list(self.params.keys())}")
            
            # Vérification et extraction des paramètres CRITIQUES
            working_folder = self.params.get('working_folder')
            if not working_folder:
                self.error.emit("Paramètre 'working_folder' manquant ou vide dans les paramètres")
                return
            
            # Stockage dans la variable d'instance pour utilisation dans toutes les méthodes
            self.working_folder = working_folder
            
            self.log.emit(f"Dossier de travail: {self.working_folder}")

            steps = [
                ("Configuration des connexions WFS", self.setup_wfs_connections),
                ("Chargement des couches WFS", self.load_wfs_layers),
                
                # ("Téléchargement ZNIEFF", self.download_znieff),
                ("Traitement descriptions ZNIEFF", self.process_znieff_desc),
                ("Traitement espèces ZNIEFF", self.process_znieff_esp),
                ("Traitement habitats ZNIEFF", self.process_znieff_hab),
                
                # ("Téléchargement Natura 2000", self.download_natura),
                ("Traitement descriptions Natura 2000", self.process_natura_desc),
                ("Traitement espèces Natura 2000", self.process_natura_esp),
                ("Traitement habitats Natura 2000", self.process_natura_hab),
                
                ("Pivot des espèces déterminantes des ZNIEFF", self.pivot_znieff_esp),
                ("Pivot des habitats des ZNIEFF", self.pivot_znieff_hab),
                ("Pivot des espèces Natura 2000", self.pivot_natura_esp),
                ("Pivot des habitats Natura 2000", self.pivot_natura_hab),
            ]
            # Flags pour bloquer les pivots si aucune donnée en amont
            self._has_znieff_esp = False
            self._has_znieff_hab = False
            self._has_natura_esp = False
            self._has_natura_hab = False

            total_steps = len(steps)
            for i, (step_name, step_function) in enumerate(steps, 1):
                self.progress.emit(i, total_steps, step_name)
                self.log.emit(f"--- Début : {step_name} ---")
                step_function()
                self.log.emit(f"--- Terminé : {step_name} ---")
                
            self.finished.emit("Moissonnage FSD terminé avec succès !")
            
        except Exception as e:
            self.error.emit(f"Erreur critique dans le workflow FSD : {str(e)}")
    
    def setup_wfs_connections(self):
        """Configure les connexions WFS nécessaires pour le moissonnage"""
        self.log.emit("Vérification et ajout des connexions WFS...")
        try:
            success, message = setup_wfs_connections()
            
            for line in message.split('\n'):
                if line.strip():
                    self.log.emit(line)
            
            if not success:
                self.log.emit("Avertissement : Certaines connexions WFS n'ont pas pu être ajoutées")
            else:
                self.log.emit("Connexions WFS configurées avec succès")
                
        except Exception as e:
            self.log.emit(f"Erreur lors de la configuration WFS : {str(e)}")
            self.log.emit("Le traitement va continuer mais certaines connexions peuvent être manquantes")

    def load_wfs_layers(self):
        """Charge les couches WFS nécessaires pour le moissonnage"""
        self.log.emit("Chargement des couches WFS dans le projet...")
        try:
            success, message = load_wfs_layers()

            for line in message.split('\n'):
                if line.strip():
                    self.log.emit(line)

            if not success:
                self.log.emit("Avertissement : Certaines couches WFS n'ont pas pu être chargées")
            else:
                self.log.emit("Couches WFS chargées avec succès")

        except Exception as e:
            self.log.emit(f"Erreur lors du chargement des couches WFS : {str(e)}")
            self.log.emit("Le traitement va continuer mais certaines couches peuvent être manquantes")

    # def download_znieff(self):
    #     self.log.emit("Téléchargement des FSD des ZNIEFF au format xml...")
    #     if not self.working_folder:
    #         self.log.emit("ERREUR: Dossier de travail non défini")
    #         return False
    #     success = znieff_download(self.working_folder)
    #     if not success: 
    #         self.log.emit("Avertissement : Échec partiel sur le téléchargement des xml des ZNIEFF")
    #     return success
    
    def process_znieff_desc(self):
        self.log.emit("Analyse des descriptions ZNIEFF...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_znieff_desc")
            return False
        success = znieff_process_desc(self.working_folder)
        if not success: 
            self.log.emit("Avertissement : Échec partiel sur les descriptions ZNIEFF")
        return success

    def process_znieff_esp(self):
        self.log.emit("Analyse des espèces ZNIEFF...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_znieff_esp")
            return
        result = znieff_process_esp(self.working_folder)
        if result is True:
            self._has_znieff_esp = True
        elif result is False:
            self.log.emit("Avertissement : Échec partiel sur les espèces ZNIEFF")
        # result None ou True sans données = ignoré silencieusement

    def process_znieff_hab(self):
        self.log.emit("Analyse des habitats ZNIEFF...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_znieff_hab")
            return
        result = znieff_process_hab(self.working_folder)
        if result is True:
            self._has_znieff_hab = True
        elif result is False:
            self.log.emit("Avertissement : Échec partiel sur les habitats ZNIEFF")

    def pivot_znieff_esp(self):
        if not self._has_znieff_esp:
            self.log.emit("Pivot espèces ZNIEFF ignoré : aucune donnée disponible")
            return
        self.log.emit("Génération pivot espèces ZNIEFF...")
        znieff_pivot_esp()

    def pivot_znieff_hab(self):
        if not self._has_znieff_hab:
            self.log.emit("Pivot habitats ZNIEFF ignoré : aucune donnée disponible")
            return        
        self.log.emit("Génération pivot habitats ZNIEFF...")
        znieff_pivot_hab()

    # def download_natura(self):
    #     self.log.emit("Téléchargement des FSD des sites Natura 2000 au format xml...")
    #     if not self.working_folder:
    #         self.log.emit("ERREUR: Dossier de travail non défini")
    #         return False
    #     success = natura_download(self.working_folder)
    #     if not success: 
    #         self.log.emit("Avertissement : Échec partiel sur le téléchargement des xml des sites Natura 2000")
    #     return success
    
    def process_natura_desc(self):
        self.log.emit("Analyse des descriptions Natura 2000...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_natura_desc")
            return False
        success = natura_process_desc(self.working_folder)
        if not success: 
            self.log.emit("Avertissement : Échec partiel sur Natura 2000")
        return success

    def process_natura_esp(self):
        self.log.emit("Analyse des espèces Natura 2000...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_natura_esp")
            return
        result = natura_process_esp(self.working_folder)
        if result is True:
            self._has_natura_esp = True
        elif result is False:
            self.log.emit("Avertissement : Échec partiel sur les espèces Natura 2000")

    def process_natura_hab(self):
        self.log.emit("Analyse des habitats Natura 2000...")
        if not self.working_folder:
            self.log.emit("ERREUR: Dossier de travail non défini pour process_natura_hab")
            return
        result = natura_process_hab(self.working_folder)
        if result is True:
            self._has_natura_hab = True
        elif result is False:
            self.log.emit("Avertissement : Échec partiel sur les habitats Natura 2000")

    def pivot_natura_esp(self):
        if not self._has_natura_esp:
            self.log.emit("Pivot espèces Natura 2000 ignoré : aucune donnée disponible")
            return        
        self.log.emit("Génération pivot espèces Natura...")
        natura_pivot_esp()

    def pivot_natura_hab(self):
        if not self._has_natura_hab:
            self.log.emit("Pivot habitats Natura 2000 ignoré : aucune donnée disponible")
            return 
        self.log.emit("Génération pivot habitats Natura...")
        natura_pivot_hab()

class TaxrefProcessingThread(QThread):
    """Thread gérant la consolidation avec TaxRef."""
    progress = pyqtSignal(int, int, str)
    log = pyqtSignal(str)
    finished = pyqtSignal(str)
    error = pyqtSignal(str)

    def __init__(self, params, iface):
        super().__init__()
        self.params = params
        self.iface = iface

    def run(self):
        try:
            self.log.emit("=== Démarrage de la consolidation TaxRef ===")
            
            # Étape unique : consolidation
            self.progress.emit(1, 1, "Consolidation avec TaxRef")
            
            if not self.params.get('consolidation_config'):
                self.log.emit("Aucune couche externe à consolider.")
                self.finished.emit("Aucune couche à consolider.")
                return
    
            self.log.emit(f"Nombre de couches à consolider : {len(self.params['consolidation_config'])}")
            
            consolidator = TaxrefApiToTable(self.params['gpkg_path'])
            success, msg = consolidator.run(self.params['consolidation_config'])
            
            self.log.emit(msg)
            
            if success:
                self.finished.emit("Consolidation TaxRef terminée avec succès !")
            else:
                self.error.emit(f"Erreur lors de la consolidation : {msg}")
                
        except Exception as e:
            self.error.emit(f"Erreur critique dans la consolidation TaxRef : {str(e)}")

class BdStatutsProcessingThread(QThread):
    """Thread gérant le workflow BD Statuts : API -> status_data -> jointure -> pivots."""
    progress = pyqtSignal(int, int, str)
    log = pyqtSignal(str)
    finished = pyqtSignal(str)
    error = pyqtSignal(str)

    def __init__(self, params, iface):
        super().__init__()
        self.params = params
        self.iface = iface

    def run(self):
        try:
            self.log.emit("=== Démarrage du workflow BD Statuts ===")
            gpkg_path = self.params.get("gpkg_path")
            code_insee = self.params.get("code_insee")
            layer_config = self.params.get("consolidation_config") or []

            if not gpkg_path:
                self.error.emit("Paramètre gpkg_path manquant.")
                return
            if not code_insee:
                self.error.emit("Département de référence non sélectionné.")
                return
            if not layer_config:
                self.error.emit("Aucune couche source (CD_Nom) configurée pour les statuts.")
                return

            def log_cb(msg):
                self.log.emit(msg)

            def progress_cb(current, total, msg):
                self.progress.emit(current, total, msg)

            # 1. API -> status_data dans GPKG
            self.progress.emit(1, 4, "Requête API Statuts (département)")
            ok, msg = status_api_to_table(
                gpkg_path, code_insee, layer_config,
                progress_callback=progress_cb, log_callback=log_cb
            )
            if not ok:
                self.error.emit(msg)
                return
            self.log.emit(msg)

            # 2. Jointure status_data + data_taxref -> status_data_joined
            self.progress.emit(2, 4, "Jointure avec data_taxref")
            ok, msg = status_join_taxref(gpkg_path, progress_callback=progress_cb, log_callback=log_cb)
            if not ok:
                self.log.emit(f"Avertissement : {msg}")
                # On continue quand même pour les pivots (sur status_data seul)
            else:
                self.log.emit(msg)

            # 3. Tables pivot par groupe
            self.progress.emit(3, 4, "Création des tables pivot par groupe")
            ok, msg = status_pivot_by_group(gpkg_path, progress_callback=progress_cb, log_callback=log_cb)
            if not ok:
                self.log.emit(f"Avertissement : {msg}")
            else:
                self.log.emit(msg)

            self.progress.emit(4, 4, "Terminé")
            self.finished.emit("Workflow BD Statuts terminé avec succès.")
        except Exception as e:
            self.error.emit(f"Erreur critique BD Statuts : {str(e)}")

class BotanixProcessingThread(QThread):
    """Thread gérant le workflow d'analyse écologique via le script R JulveDfToMembershipDf."""
    progress = pyqtSignal(int, int, str)
    log      = pyqtSignal(str)
    finished = pyqtSignal(str)
    error    = pyqtSignal(str)

    def __init__(self, params, iface):
        super().__init__()
        self.params = params
        self.iface  = iface

    def run(self):
        try:
            self.log.emit("=== Démarrage du workflow Botanix (Julve → Membership) ===")

            working_folder = self.params.get("working_folder")
            input_file     = self.params.get("input_file")

            # Vérifications des paramètres
            if not working_folder or not os.path.isdir(working_folder):
                self.error.emit("Paramètre 'working_folder' manquant ou dossier introuvable.")
                return
            if not input_file:
                self.error.emit("Paramètre 'input_file' manquant (nom du fichier CSV à analyser).")
                return

            steps = [
                ("Vérification du fournisseur R", self.check_r_provider),
                ("Construction du tableau Julve", self.build_julve_csv),
                ("Lancement de l'analyse Julve / Membership", self.run_julve_algorithm),
            ]

            total = len(steps)
            for i, (step_name, step_fn) in enumerate(steps, 1):
                self.progress.emit(i, total, step_name)
                self.log.emit(f"--- Début : {step_name} ---")
                step_fn()
                self.log.emit(f"--- Terminé : {step_name} ---")

            self.finished.emit("Analyse Botanix terminée avec succès !")

        except Exception as e:
            self.error.emit(f"Erreur critique dans le workflow Botanix : {str(e)}")

    def check_r_provider(self):
        """Vérifie que le Processing R Provider est configuré et que le script est disponible."""
        from qgis.core import QgsApplication

        try:
            from processing_r.processing.utils import RUtils
        except ImportError:
            raise RuntimeError(
                "Le fournisseur R (Processing R Provider) n'est pas disponible. "
                "Installez et activez l'extension « Processing R Provider »."
            )

        provider = QgsApplication.processingRegistry().providerById("r")
        if not provider:
            raise RuntimeError(
                "Le fournisseur R n'est pas chargé. "
                "Vérifiez que l'extension « Processing R Provider » est activée."
            )

        r_folder = RUtils.r_binary_folder()
        if not r_folder or not os.path.isdir(r_folder):
            raise RuntimeError(
                "Dossier R non configuré. Allez dans Traitement → Options → Fournisseurs → R."
            )

        algorithm_id = "r:JulveDfToMembershipDf"
        if not QgsApplication.processingRegistry().algorithmById(algorithm_id):
            script_dirs = ", ".join(RUtils.script_folders())
            raise RuntimeError(
                "Script R « JulveDfToMembershipDf » introuvable. "
                f"Dossiers de scripts consultés : {script_dirs}. "
                "Réinstallez le plugin Biblizou ou vérifiez le dossier de scripts R."
            )

        self.log.emit(f"Fournisseur R OK — {r_folder}")

    def build_julve_csv(self):
        """Génère JulveDf.csv depuis les couches sélectionnées + baseflor."""
        layer_config = self.params.get("consolidation_config", [])
        if not layer_config:
            raise RuntimeError("Aucune couche source configurée dans l'onglet Botanix.")

        working_folder = self.params["working_folder"]
        builder = BuildJulveDf(working_folder)
        builder.status_changed.connect(self.log)

        success, msg = builder.run(layer_config)
        self.log.emit(msg)

        if not success:
            raise RuntimeError(f"Échec de la construction du tableau Julve : {msg}")

    def run_julve_algorithm(self):
        """Lance JulveDfToMembershipDf via le Processing R Provider de QGIS."""
        from qgis import processing
        from qgis.core import QgsProcessingContext, QgsProcessingFeedback

        plugin_dir = os.path.dirname(__file__)
        julve_labels = os.path.join(plugin_dir, "config", "julve_labels.json")

        if not os.path.isfile(julve_labels):
            raise RuntimeError(f"Fichier julve_labels.json introuvable : {julve_labels}")

        # Normalisation des chemins Windows pour R
        working_folder = self.params["working_folder"].replace("\\", "/")
        julve_labels = julve_labels.replace("\\", "/")

        feedback = QgsProcessingFeedback()
        context = QgsProcessingContext()

        params = {
            "folder_path": working_folder,
            "input_file": self.params.get("input_file", "julve_df.csv"),
            "julve_labels": julve_labels,
        }

        result = processing.run(
            "r:JulveDfToMembershipDf",
            params,
            context=context,
            feedback=feedback,
        )

        console_output = result.get("R_CONSOLE_OUTPUT", "")
        if console_output:
            self.log.emit(console_output)

        self.log.emit("Analyse Julve / Membership exécutée avec succès.")