# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BiblizouDockWidget
                                 A QGIS plugin
 Moissonnage bibliographique automatisé
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by François Botcazou
        email                : francois.botcazou@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtGui, QtWidgets, QtCore, uic
from qgis.PyQt.QtCore import pyqtSignal, QSize, Qt
from PyQt5.QtWidgets import QPushButton, QHeaderView, QCompleter
from qgis.core import Qgis, QgsMessageLog, QgsMapLayerProxyModel
from qgis.gui import QgsFileWidget, QgsMapLayerComboBox, QgsFieldComboBox


# Importation du thread de traitement depuis le script biblizou.py
try:
    from .biblizou_worker import FsdProcessingThread, TaxrefProcessingThread, BdStatutsProcessingThread, BotanixProcessingThread
except ImportError:
    from biblizou_worker import FsdProcessingThread, TaxrefProcessingThread, BdStatutsProcessingThread, BotanixProcessingThread

import sys
from . import resources as resources_rc

# Import du dialog patrimonialité
try:
    from .biblizou_dialog_patri import BiblizouDialogPatri
except ImportError:
    from biblizou_dialog_patri import BiblizouDialogPatri


sys.modules['resources_rc'] = resources_rc

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'biblizou_dockwidget_base.ui'))


class BiblizouDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface, parent=None):
        """Constructor."""
        super(BiblizouDockWidget, self).__init__(parent)
        self.iface = iface
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Configuration du tableau TaxRef
        header = self.tableTaxref.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.Stretch)
        header.setSectionResizeMode(1, QHeaderView.Stretch)
        header.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        
        # Connexion du bouton d'ajout de ligne pour TaxRef
        self.btnAddLayerRowTaxtef.clicked.connect(self.add_taxref_row)
        
        # Initialisation des widgets spécifiques à QGIS
        self.setup_custom_widgets()

        # Connexion des boutons (Noms basés sur le nouveau fichier .ui)
        self.btnRunFsd.clicked.connect(self.run_fsd_process)
        self.btnRunTaxref.clicked.connect(self.run_taxref_process)
        self.btnRunStat.clicked.connect(self.run_stat_process)
        
        # Tableau BD Statuts (même principe que TaxRef)
        self.btnAddLayerRowStat.clicked.connect(self.add_stat_row)
        header_stat = self.tableStat.horizontalHeader()
        if header_stat:
            header_stat.setSectionResizeMode(0, QHeaderView.Stretch)
            header_stat.setSectionResizeMode(1, QHeaderView.Stretch)
            header_stat.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        
        # Liste déroulante département (filtrable, stocke code_insee)
        self.setup_department_combo()
        
        # Variables pour stocker les threads
        self.fsd_thread = None
        self.taxref_thread = None
        self.stat_thread = None

        # Thread et dialog Botanix
        self.botanix_thread = None
        self.dialog_patri = None

        # SpinBox flou : valeur par défaut 2, affichage "auto (2)"
        self.spinBoxFuzzyBotanix.setMinimum(0)
        self.spinBoxFuzzyBotanix.setMaximum(10)
        self.spinBoxFuzzyBotanix.setValue(2)
        self.spinBoxFuzzyBotanix.setSpecialValueText("")  # pas de texte spécial sur 0
        self.spinBoxFuzzyBotanix.setPrefix("auto (")
        self.spinBoxFuzzyBotanix.setSuffix(")")

        # Onglet Botanix — connexions
        self.btnAddLayerRowBotanix.clicked.connect(self.add_botanix_row)
        self.btnRunBotanix.clicked.connect(self.run_botanix_process)
        self.rBPatriBotanix.toggled.connect(self.on_patri_toggled)
        self.pBPatriBotanix.clicked.connect(self.open_dialog_patri)
        self.pBPatriBotanix.setEnabled(self.rBPatriBotanix.isChecked())

        # En-têtes du tableau Botanix
        header_botanix = self.tableBotanix.horizontalHeader()
        if header_botanix:
            header_botanix.setSectionResizeMode(0, QHeaderView.Stretch)
            header_botanix.setSectionResizeMode(1, QHeaderView.Stretch)
            header_botanix.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        
    def setup_custom_widgets(self):
        """Configure les filtres et modes des widgets QGIS."""
        # Filtrer pour ne montrer que les couches polygonales
        self.mapLayerN2k.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.mapLayerZnieff.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
        # Configurer le sélecteur de dossier
        self.mQgsFileWidget.setStorageMode(QgsFileWidget.GetDirectory)
        self.mQgsFileWidget.setDialogTitle("Sélectionner le dossier de travail")

    def setup_department_combo(self):
        """Remplit le combo Département depuis dept_fr.csv (nom_officiel affiché, code_insee stocké). Liste filtrable."""
        import csv
        csv_path = os.path.join(os.path.dirname(__file__), "config", "dept_fr.csv")
        self.comboBoxDpt.clear()
        if not os.path.isfile(csv_path):
            QgsMessageLog.logMessage("Biblizou: dept_fr.csv introuvable", "Biblizou", level=Qgis.Warning)
            return
        try:
            with open(csv_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    nom = (row.get("nom_officiel") or "").strip()
                    code = (row.get("code_insee") or "").strip().strip('"')
                    if nom and code:
                        self.comboBoxDpt.addItem(nom, code)
            self.comboBoxDpt.setEditable(True)
            c = QCompleter(self.comboBoxDpt.model())
            c.setFilterMode(Qt.MatchContains)
            c.setCaseSensitivity(Qt.CaseInsensitive)
            
            # Forcer la vue de complétion à adopter le style de liste
            c.popup().setStyleSheet(self.comboBoxDpt.styleSheet())
            
            self.comboBoxDpt.setCompleter(c)
        except Exception as e:
            QgsMessageLog.logMessage(f"Biblizou: Erreur chargement dept_fr.csv : {e}", "Biblizou", level=Qgis.Warning)

    def get_fsd_parameters(self):
        """Récupère les données saisies par l'utilisateur pour le workflow FSD."""
        # On ne passe que le working_folder, pas les objets layer
        return {
            'working_folder': self.mQgsFileWidget.filePath()
        }

    def validate_fsd(self):
        """Valide la saisie avant exécution du workflow FSD."""
        errors = []

        if not self.mapLayerZnieff.currentLayer():
            errors.append("Couche ZNIEFF manquante.")
        if not self.mapLayerN2k.currentLayer():
            errors.append("Couche Natura 2000 manquante.")
        
        working_folder = self.mQgsFileWidget.filePath()
        if not working_folder or not os.path.isdir(working_folder):
            errors.append("Dossier de travail invalide.")

        if errors:
            QtWidgets.QMessageBox.warning(self, "Validation", "\n".join(errors))
            return False
        return True

    def add_taxref_row(self):
        """Ajoute une ligne au tableau de consolidation TaxRef."""
        row = self.tableTaxref.rowCount()
        self.tableTaxref.insertRow(row)
        
        lyr_cb = QgsMapLayerComboBox()
        lyr_cb.setFilters(QgsMapLayerProxyModel.VectorLayer)
        fld_cb = QgsFieldComboBox()
        fld_cb.setLayer(lyr_cb.currentLayer())
        lyr_cb.layerChanged.connect(fld_cb.setLayer)
        
        btn_del = QPushButton()
        icon_path = os.path.join(os.path.dirname(__file__), 'misc', 'cross.png')
        btn_del.setIcon(QtGui.QIcon(icon_path))
        btn_del.setIconSize(QtCore.QSize(16, 16))
        btn_del.setMaximumWidth(30)
        btn_del.clicked.connect(lambda: self.tableTaxref.removeRow(self.tableTaxref.indexAt(btn_del.pos()).row()))
        
        self.tableTaxref.setCellWidget(row, 0, lyr_cb)
        self.tableTaxref.setCellWidget(row, 1, fld_cb)
        self.tableTaxref.setCellWidget(row, 2, btn_del)

    def get_taxref_consolidation_data(self):
        """Extrait proprement les IDs et colonnes du tableau TaxRef."""
        data = []
        for row in range(self.tableTaxref.rowCount()):
            lyr_widget = self.tableTaxref.cellWidget(row, 0)
            fld_widget = self.tableTaxref.cellWidget(row, 1)
            
            if lyr_widget and lyr_widget.currentLayer():
                data.append({
                    'layer_id': lyr_widget.currentLayer().id(),
                    'column': fld_widget.currentField()
                })
        return data

    def validate_taxref(self):
        """Valide la saisie avant exécution de la consolidation TaxRef."""
        working_folder = self.mQgsFileWidget.filePath()
        errors = []

        if not working_folder or not os.path.isdir(working_folder):
            errors.append("Dossier de travail invalide.")
        
        consolidation_data = self.get_taxref_consolidation_data()
        if not consolidation_data:
            errors.append("Aucune couche à consolider avec TaxRef.")

        if errors:
            QtWidgets.QMessageBox.warning(self, "Validation", "\n".join(errors))
            return False
        return True

    def run_fsd_process(self):
        """Lance le traitement FSD via le thread."""
        if not self.validate_fsd():
            return

        # On ne passe que le working_folder
        params = {
            'working_folder': self.mQgsFileWidget.filePath()
        }
        
        QgsMessageLog.logMessage(f"Params avant création thread: {params}", "Biblizou", level=Qgis.Info)
        QgsMessageLog.logMessage(f"Working folder: {params.get('working_folder')}", "Biblizou", level=Qgis.Info)
        
        # Confirmation
        msg = f"Lancer le moissonnage des données FSD ?\n\nDossier : {params['working_folder']}"
        reply = QtWidgets.QMessageBox.question(self, "Confirmation", msg, 
                                               QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        
        if reply == QtWidgets.QMessageBox.Yes:
            self.btnRunFsd.setEnabled(False)
            
            # Initialisation du thread FSD
            self.fsd_thread = FsdProcessingThread(params, self.iface)
            
            # Connexion des signaux du thread
            self.fsd_thread.progress.connect(self.update_status_bar)
            self.fsd_thread.log.connect(self.log_to_qgis)
            self.fsd_thread.finished.connect(self.on_fsd_finished)
            self.fsd_thread.error.connect(self.on_error)
            
            self.fsd_thread.start()
            self.iface.messageBar().pushMessage("Biblizou", "Traitement FSD démarré...", level=Qgis.Info)

    def run_taxref_process(self):
        """Lance la consolidation TaxRef via le thread."""
        if not self.validate_taxref():
            return

        params = {
            'working_folder': self.mQgsFileWidget.filePath(),
            'consolidation_config': self.get_taxref_consolidation_data(),
            'gpkg_path': os.path.join(self.mQgsFileWidget.filePath(), "biblizou.gpkg")
        }
        
        # Confirmation
        msg = f"Lancer la consolidation avec TaxRef ?\n\n{len(params['consolidation_config'])} couche(s) à traiter"
        reply = QtWidgets.QMessageBox.question(self, "Confirmation", msg, 
                                               QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        
        if reply == QtWidgets.QMessageBox.Yes:
            self.btnRunTaxref.setEnabled(False)
            
            # Initialisation du thread TaxRef
            self.taxref_thread = TaxrefProcessingThread(params, self.iface)
            
            # Connexion des signaux du thread
            self.taxref_thread.progress.connect(self.update_status_bar)
            self.taxref_thread.log.connect(self.log_to_qgis)
            self.taxref_thread.finished.connect(self.on_taxref_finished)
            self.taxref_thread.error.connect(self.on_error)
            
            self.taxref_thread.start()
            self.iface.messageBar().pushMessage("Biblizou", "Consolidation TaxRef démarrée...", level=Qgis.Info)

    def update_status_bar(self, step, total, message):
        """Affiche la progression dans la barre de message de QGIS."""
        self.iface.mainWindow().statusBar().showMessage(f"Biblizou : {message} ({step}/{total})")

    def log_to_qgis(self, message):
        """Envoie les logs vers le panneau QGIS."""
        QgsMessageLog.logMessage(message, "Biblizou", level=Qgis.Info)

    def on_fsd_finished(self, message):
        """Action à la fin du traitement FSD."""
        self.btnRunFsd.setEnabled(True)
        QtWidgets.QMessageBox.information(self, "Succès", message)
        self.iface.mainWindow().statusBar().clearMessage()

    def on_taxref_finished(self, message):
        """Action à la fin de la consolidation TaxRef."""
        self.btnRunTaxref.setEnabled(True)
        QtWidgets.QMessageBox.information(self, "Succès", message)
        self.iface.mainWindow().statusBar().clearMessage()

    def add_stat_row(self):
        """Ajoute une ligne au tableau BD Statuts (couche + champ CD_Nom)."""
        row = self.tableStat.rowCount()
        self.tableStat.insertRow(row)
        lyr_cb = QgsMapLayerComboBox()
        lyr_cb.setFilters(QgsMapLayerProxyModel.VectorLayer)
        fld_cb = QgsFieldComboBox()
        fld_cb.setLayer(lyr_cb.currentLayer())
        lyr_cb.layerChanged.connect(fld_cb.setLayer)
        btn_del = QPushButton()
        icon_path = os.path.join(os.path.dirname(__file__), 'misc', 'cross.png')
        btn_del.setIcon(QtGui.QIcon(icon_path))
        btn_del.setIconSize(QtCore.QSize(16, 16))
        btn_del.setMaximumWidth(30)
        btn_del.clicked.connect(lambda: self.tableStat.removeRow(self.tableStat.indexAt(btn_del.pos()).row()))
        self.tableStat.setCellWidget(row, 0, lyr_cb)
        self.tableStat.setCellWidget(row, 1, fld_cb)
        self.tableStat.setCellWidget(row, 2, btn_del)

    def get_stat_config(self):
        """Extrait les IDs et colonnes du tableau BD Statuts (pour collecte cd_nom)."""
        data = []
        for row in range(self.tableStat.rowCount()):
            lyr_widget = self.tableStat.cellWidget(row, 0)
            fld_widget = self.tableStat.cellWidget(row, 1)
            if lyr_widget and lyr_widget.currentLayer():
                data.append({
                    "layer_id": lyr_widget.currentLayer().id(),
                    "column": fld_widget.currentField()
                })
        return data

    def validate_stat(self):
        """Valide la saisie avant exécution du workflow BD Statuts."""
        errors = []
        working_folder = self.mQgsFileWidget.filePath()
        if not working_folder or not os.path.isdir(working_folder):
            errors.append("Dossier de travail invalide.")
        code_insee = self.comboBoxDpt.currentData()
        if not code_insee:
            errors.append("Veuillez sélectionner un département (liste filtrable sur le nom).")
        if not self.get_stat_config():
            errors.append("Ajoutez au moins une couche avec un attribut CD_Nom pour les statuts.")
        if errors:
            QtWidgets.QMessageBox.warning(self, "Validation BD Statuts", "\n".join(errors))
            return False
        return True

    def run_stat_process(self):
        """Lance le workflow BD Statuts (API -> status_data -> jointure -> pivots)."""
        if not self.validate_stat():
            return
        working_folder = self.mQgsFileWidget.filePath()
        params = {
            "working_folder": working_folder,
            "gpkg_path": os.path.join(working_folder, "biblizou.gpkg"),
            "code_insee": self.comboBoxDpt.currentData(),
            "consolidation_config": self.get_stat_config()
        }
        msg = (
            f"Lancer le workflow BD Statuts ?\n\n"
            f"Département : {self.comboBoxDpt.currentText()} (code {params['code_insee']})\n"
            f"Couches : {len(params['consolidation_config'])}\n"
            f"GeoPackage : {params['gpkg_path']}"
        )
        reply = QtWidgets.QMessageBox.question(
            self, "Confirmation", msg,
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if reply != QtWidgets.QMessageBox.Yes:
            return
        self.btnRunStat.setEnabled(False)
        self.stat_thread = BdStatutsProcessingThread(params, self.iface)
        self.stat_thread.progress.connect(self.update_status_bar)
        self.stat_thread.log.connect(self.log_to_qgis)
        self.stat_thread.finished.connect(self.on_stat_finished)
        self.stat_thread.error.connect(self.on_error_stat)
        self.stat_thread.start()
        self.iface.messageBar().pushMessage("Biblizou", "Workflow BD Statuts démarré...", level=Qgis.Info)

    def on_stat_finished(self, message):
        """Action à la fin du workflow BD Statuts."""
        self.btnRunStat.setEnabled(True)
        QtWidgets.QMessageBox.information(self, "Succès", message)
        self.iface.mainWindow().statusBar().clearMessage()

    def on_error_stat(self, error_message):
        """Action en cas d'erreur du workflow BD Statuts."""
        self.btnRunStat.setEnabled(True)
        QtWidgets.QMessageBox.critical(self, "Erreur BD Statuts", error_message)

    # ------------------------------------------------------------------ #
    #  Onglet Botanix                                                      #
    # ------------------------------------------------------------------ #

    def on_patri_toggled(self, checked):
        """Active/désactive le bouton 'Gérer patrimonialité' selon l'état du radio."""
        self.pBPatriBotanix.setEnabled(checked)

    def open_dialog_patri(self):
        """Ouvre le dialog de gestion de la patrimonialité."""
        if self.dialog_patri is None:
            self.dialog_patri = BiblizouDialogPatri(self)
        self.dialog_patri.show()
        self.dialog_patri.raise_()
        self.dialog_patri.activateWindow()

    def add_botanix_row(self):
        """Ajoute une ligne au tableau Botanix (couche + champ CD_Nom/Ref)."""
        row = self.tableBotanix.rowCount()
        self.tableBotanix.insertRow(row)
        lyr_cb = QgsMapLayerComboBox()
        lyr_cb.setFilters(QgsMapLayerProxyModel.VectorLayer)
        fld_cb = QgsFieldComboBox()
        fld_cb.setLayer(lyr_cb.currentLayer())
        lyr_cb.layerChanged.connect(fld_cb.setLayer)
        btn_del = QPushButton()
        icon_path = os.path.join(os.path.dirname(__file__), 'misc', 'cross.png')
        btn_del.setIcon(QtGui.QIcon(icon_path))
        btn_del.setIconSize(QtCore.QSize(16, 16))
        btn_del.setMaximumWidth(30)
        btn_del.clicked.connect(lambda: self.tableBotanix.removeRow(
            self.tableBotanix.indexAt(btn_del.pos()).row()))
        self.tableBotanix.setCellWidget(row, 0, lyr_cb)
        self.tableBotanix.setCellWidget(row, 1, fld_cb)
        self.tableBotanix.setCellWidget(row, 2, btn_del)

    def get_botanix_config(self):
        """Extrait les couches et champs du tableau Botanix."""
        data = []
        for row in range(self.tableBotanix.rowCount()):
            lyr_widget = self.tableBotanix.cellWidget(row, 0)
            fld_widget = self.tableBotanix.cellWidget(row, 1)
            if lyr_widget and lyr_widget.currentLayer():
                data.append({
                    "layer_id": lyr_widget.currentLayer().id(),
                    "column": fld_widget.currentField()
                })
        return data

    def validate_botanix(self):
        """Valide la saisie avant exécution du workflow Botanix."""
        errors = []
        working_folder = self.mQgsFileWidget.filePath()
        if not working_folder or not os.path.isdir(working_folder):
            errors.append("Dossier de travail invalide.")
        if not self.get_botanix_config():
            errors.append("Ajoutez au moins une couche source dans l'onglet Botanix.")
        if errors:
            QtWidgets.QMessageBox.warning(self, "Validation Botanix", "\n".join(errors))
            return False
        return True

    def run_botanix_process(self):
        """Lance le workflow Botanix (DCA → Membership) via le thread."""
        if not self.validate_botanix():
            return

        working_folder = self.mQgsFileWidget.filePath()
        only_patrimonial = self.rBPatriBotanix.isChecked()
        fuzzy_value = self.spinBoxFuzzyBotanix.value()

        params = {
            "working_folder": working_folder,
            "input_file": "dca_data.csv",
            "only_patrimonial": only_patrimonial,
            "fuzzy_threshold": fuzzy_value,
            "consolidation_config": self.get_botanix_config()
        }

        msg = (
            f"Lancer l'analyse Botanix ?\n\n"
            f"Dossier : {working_folder}\n"
            f"Couches : {len(params['consolidation_config'])}\n"
            f"Espèces patrimoniales uniquement : {'Oui' if only_patrimonial else 'Non'}\n"
            f"Réglage du flou : auto ({fuzzy_value})"
        )
        reply = QtWidgets.QMessageBox.question(
            self, "Confirmation", msg,
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if reply != QtWidgets.QMessageBox.Yes:
            return

        self.btnRunBotanix.setEnabled(False)
        self.botanix_thread = BotanixProcessingThread(params, self.iface)
        self.botanix_thread.progress.connect(self.update_status_bar)
        self.botanix_thread.log.connect(self.log_to_qgis)
        self.botanix_thread.finished.connect(self.on_botanix_finished)
        self.botanix_thread.error.connect(self.on_error_botanix)
        self.botanix_thread.start()
        self.iface.messageBar().pushMessage("Biblizou", "Analyse Botanix démarrée...", level=Qgis.Info)

    def on_botanix_finished(self, message):
        """Action à la fin du workflow Botanix."""
        self.btnRunBotanix.setEnabled(True)
        QtWidgets.QMessageBox.information(self, "Succès", message)
        self.iface.mainWindow().statusBar().clearMessage()

    def on_error_botanix(self, error_message):
        """Action en cas d'erreur du workflow Botanix."""
        self.btnRunBotanix.setEnabled(True)
        QtWidgets.QMessageBox.critical(self, "Erreur Botanix", error_message)

    def on_error(self, error_message):
        """Action en cas d'erreur."""
        self.btnRunFsd.setEnabled(True)
        self.btnRunTaxref.setEnabled(True)
        self.btnRunStat.setEnabled(True)
        self.btnRunBotanix.setEnabled(True)
        QtWidgets.QMessageBox.critical(self, "Erreur", error_message)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()